package frc.robot.constants;

// Generated by PowerLib subsystem tool. Edit power-tool/generated/powerlib-subsystems.json, then run update.
// POWERLIB SUBSYSTEM ID: intakeRoller

import com.ctre.phoenix6.signals.NeutralModeValue;
import frc.powerlib.configs.LeadMotorConfig;
import frc.powerlib.configs.MotionMagicConfig;
import frc.powerlib.configs.MotorConfig;
import frc.powerlib.configs.VelocitySubsystemConfig;
import java.util.List;
import java.util.Optional;

public class IntakeRollerConstants {
  public static final int LEADER_MOTOR_ID = 20;
  public static final NeutralModeValue LEADER_NEUTRAL_MODE = NeutralModeValue.Coast;
  public static final boolean LEADER_REVERSED = false;
  public static final double KP = 0.4;
  public static final double KI = 0;
  public static final double KD = 0;
  public static final double KG = 0;
  public static final Optional<Double> KS = Optional.of(0.0);
  public static final Optional<Double> KV = Optional.of(0.0);
  public static final Optional<Double> KA = Optional.of(0.0);
  public static final double SENSOR_TO_MECHANISM_RATIO = 1;
  public static final double ROTOR_TO_SENSOR_RATIO = 1;
  public static final boolean FOC_ENABLED = true;
  public static final double TORQUE_FF = 15.0;
  public static final double MOTION_MAGIC_CRUISE_VELOCITY = 0;
  public static final double MOTION_MAGIC_ACCELERATION = 200;
  public static final String NAME = "IntakeRoller";

  public static final VelocitySubsystemConfig INTAKE_ROLLER_CONFIG =
      new VelocitySubsystemConfig(
          List.of(
              MotorConfig.leader(LEADER_MOTOR_ID, LEADER_NEUTRAL_MODE, LEADER_REVERSED)),
          new LeadMotorConfig(
              KP,
              KI,
              KD,
              KG,
              KS,
              KV,
              KA,
              SENSOR_TO_MECHANISM_RATIO,
              ROTOR_TO_SENSOR_RATIO,
              FOC_ENABLED),
          new MotionMagicConfig(MOTION_MAGIC_CRUISE_VELOCITY, MOTION_MAGIC_ACCELERATION),
          NAME,
          TORQUE_FF);

  // POWERLIB CUSTOM CONSTANTS START - DO NOT DELETE
  @frc.powerlib.tuning.TunableConstant
  public static volatile double INTAKE_DOWN_SETPOINT = 0;
  @frc.powerlib.tuning.TunableConstant
  public static volatile double INTAKE_UP_SETPOINT = 0;
  @frc.powerlib.tuning.TunableConstant
  public static volatile double INTAKE_ROLLER_OUTPUT = 0.8;
  @frc.powerlib.tuning.TunableConstant
  public static volatile double ROLLER_TARGET_RPS = 10;
  // POWERLIB CUSTOM CONSTANTS END - DO NOT DELETE
}
