package frc.robot.constants;

// Generated by PowerLib subsystem tool. Edit power-tool/generated/powerlib-subsystems.json, then run update.
// POWERLIB SUBSYSTEM ID: intakeWrist

import com.ctre.phoenix6.signals.NeutralModeValue;
import frc.powerlib.configs.CancoderConfig;
import frc.powerlib.configs.LeadMotorConfig;
import frc.powerlib.configs.MotionMagicConfig;
import frc.powerlib.configs.MotorConfig;
import frc.powerlib.configs.AbsolutePositionSubsystemConfig;
import java.util.List;
import java.util.Optional;

public class IntakeWristConstants {
  public static final int LEADER_MOTOR_ID = 21;
  public static final NeutralModeValue LEADER_NEUTRAL_MODE = NeutralModeValue.Brake;
  public static final boolean LEADER_REVERSED = false;
  public static final int FOLLOWER_1_MOTOR_ID = 22;
  public static final NeutralModeValue FOLLOWER_1_NEUTRAL_MODE = NeutralModeValue.Brake;
  public static final boolean FOLLOWER_1_REVERSED = true;
  public static final double KP = 30;
  public static final double KI = 0;
  public static final double KD = 0;
  public static final double KG = 0;
  public static final Optional<Double> KS = Optional.of(0.0);
  public static final Optional<Double> KV = Optional.of(0.0);
  public static final Optional<Double> KA = Optional.of(0.0);
  public static final double SENSOR_TO_MECHANISM_RATIO = -1;
  public static final double ROTOR_TO_SENSOR_RATIO = 44.444;
  public static final boolean FOC_ENABLED = false;
  public static final int CANCODER_ID = 23;
  public static final double CANCODER_MAGNET_OFFSET = -0.03;
  public static final double CANCODER_DISCONTINUITY_POINT = 0.5;
  public static final double MOTION_MAGIC_CRUISE_VELOCITY = 1;
  public static final double MOTION_MAGIC_ACCELERATION = 20;
  public static final String NAME = "IntakeWrist";
  public static final String POSITION_UNITS = "degrees";
  public static final Optional<Double> DEFAULT_POSITION = Optional.of(-0.09);

  public static final AbsolutePositionSubsystemConfig INTAKE_WRIST_CONFIG =
      new AbsolutePositionSubsystemConfig(
          List.of(
              MotorConfig.leader(LEADER_MOTOR_ID, LEADER_NEUTRAL_MODE, LEADER_REVERSED),
              MotorConfig.follower(FOLLOWER_1_MOTOR_ID, FOLLOWER_1_NEUTRAL_MODE, FOLLOWER_1_REVERSED)),
          new LeadMotorConfig(
              KP,
              KI,
              KD,
              KG,
              KS,
              KV,
              KA,
              SENSOR_TO_MECHANISM_RATIO,
              ROTOR_TO_SENSOR_RATIO,
              FOC_ENABLED),
          new CancoderConfig(CANCODER_ID, CANCODER_MAGNET_OFFSET, CANCODER_DISCONTINUITY_POINT),
          new MotionMagicConfig(MOTION_MAGIC_CRUISE_VELOCITY, MOTION_MAGIC_ACCELERATION),
          NAME,
          POSITION_UNITS,
          DEFAULT_POSITION);

  // POWERLIB CUSTOM CONSTANTS START - DO NOT DELETE
  @frc.powerlib.tuning.TunableConstant
  public static volatile double INTAKE_MIN = -0.09;
  @frc.powerlib.tuning.TunableConstant
  public static volatile double INTAKE_MAX = -0.453;
  @frc.powerlib.tuning.TunableConstant
  public static volatile double INTAKE_IDLE = -0.4;
  @frc.powerlib.tuning.TunableConstant
  public static volatile double INTAKE_FEED = -0.25;
  @frc.powerlib.tuning.TunableConstant
  public static volatile double INTAKE_DEFAULT = -0.09;
  // POWERLIB CUSTOM CONSTANTS END - DO NOT DELETE
}
