package frc.robot.constants;

// Generated by PowerLib subsystem tool. Edit power-tool/generated/powerlib-subsystems.json, then run update.
// POWERLIB SUBSYSTEM ID: shooterHood

import com.ctre.phoenix6.signals.NeutralModeValue;
import frc.powerlib.configs.CancoderConfig;
import frc.powerlib.configs.LeadMotorConfig;
import frc.powerlib.configs.MotionMagicConfig;
import frc.powerlib.configs.MotorConfig;
import frc.powerlib.configs.AbsolutePositionSubsystemConfig;
import java.util.List;
import java.util.Optional;

public class ShooterHoodConstants {
  public static final int LEADER_MOTOR_ID = 50;
  public static final NeutralModeValue LEADER_NEUTRAL_MODE = NeutralModeValue.Brake;
  public static final boolean LEADER_REVERSED = true;
  public static final double KP = 10;
  public static final double KI = 0;
  public static final double KD = 2;
  public static final double KG = 0;
  public static final Optional<Double> KS = Optional.of(0.0);
  public static final Optional<Double> KV = Optional.of(0.0);
  public static final Optional<Double> KA = Optional.of(0.0);
  public static final double SENSOR_TO_MECHANISM_RATIO = -1;
  public static final double ROTOR_TO_SENSOR_RATIO = 60;
  public static final boolean FOC_ENABLED = false;
  public static final int CANCODER_ID = 54;
  public static final double CANCODER_MAGNET_OFFSET = -0.941;
  public static final double CANCODER_DISCONTINUITY_POINT = 0.5;
  public static final double MOTION_MAGIC_CRUISE_VELOCITY = 15;
  public static final double MOTION_MAGIC_ACCELERATION = 30;
  public static final String NAME = "ShooterHood";
  public static final String POSITION_UNITS = "degrees";
  public static final Optional<Double> DEFAULT_POSITION = Optional.of(0.09);

  public static final AbsolutePositionSubsystemConfig SHOOTER_HOOD_CONFIG =
      new AbsolutePositionSubsystemConfig(
          List.of(
              MotorConfig.leader(LEADER_MOTOR_ID, LEADER_NEUTRAL_MODE, LEADER_REVERSED)),
          new LeadMotorConfig(
              KP,
              KI,
              KD,
              KG,
              KS,
              KV,
              KA,
              SENSOR_TO_MECHANISM_RATIO,
              ROTOR_TO_SENSOR_RATIO,
              FOC_ENABLED),
          new CancoderConfig(CANCODER_ID, CANCODER_MAGNET_OFFSET, CANCODER_DISCONTINUITY_POINT),
          new MotionMagicConfig(MOTION_MAGIC_CRUISE_VELOCITY, MOTION_MAGIC_ACCELERATION),
          NAME,
          POSITION_UNITS,
          DEFAULT_POSITION);

  // POWERLIB CUSTOM CONSTANTS START - DO NOT DELETE
  @frc.powerlib.tuning.TunableConstant
  public static volatile double SHOOTER_HOOD_MIN = 0.005;
  @frc.powerlib.tuning.TunableConstant
  public static volatile double SHOOTER_HOOD_MAX = 0.14;
  @frc.powerlib.tuning.TunableConstant
  public static volatile double SHOOTER_HOOD_DEFAULT = 0.09;
  // POWERLIB CUSTOM CONSTANTS END - DO NOT DELETE
}
