package frc.robot.constants;

// Generated by PowerLib subsystem tool. Edit power-tool/generated/powerlib-subsystems.json, then run update.
// POWERLIB SUBSYSTEM ID: shooter

import com.ctre.phoenix6.signals.NeutralModeValue;
import frc.powerlib.configs.LeadMotorConfig;
import frc.powerlib.configs.MotionMagicConfig;
import frc.powerlib.configs.MotorConfig;
import frc.powerlib.configs.VelocitySubsystemConfig;
import java.util.List;
import java.util.Optional;

public class ShooterConstants {
  public static final int LEADER_MOTOR_ID = 51;
  public static final NeutralModeValue LEADER_NEUTRAL_MODE = NeutralModeValue.Coast;
  public static final boolean LEADER_REVERSED = true;
  public static final int FOLLOWER_1_MOTOR_ID = 52;
  public static final NeutralModeValue FOLLOWER_1_NEUTRAL_MODE = NeutralModeValue.Coast;
  public static final boolean FOLLOWER_1_REVERSED = true;
  public static final int FOLLOWER_2_MOTOR_ID = 53;
  public static final NeutralModeValue FOLLOWER_2_NEUTRAL_MODE = NeutralModeValue.Coast;
  public static final boolean FOLLOWER_2_REVERSED = true;
  public static final double KP = 0.0001;
  public static final double KI = 0;
  public static final double KD = 0;
  public static final double KG = 0;
  public static final Optional<Double> KS = Optional.of(0.28159);
  public static final Optional<Double> KV = Optional.of(0.12365);
  public static final Optional<Double> KA = Optional.of(0.003086);
  public static final double SENSOR_TO_MECHANISM_RATIO = 1;
  public static final double ROTOR_TO_SENSOR_RATIO = 1;
  public static final boolean FOC_ENABLED = true;
  public static final double TORQUE_FF = 0.0;
  public static final double MOTION_MAGIC_CRUISE_VELOCITY = 0;
  public static final double MOTION_MAGIC_ACCELERATION = 200;
  public static final String NAME = "Shooter";

  public static final VelocitySubsystemConfig SHOOTER_CONFIG =
      new VelocitySubsystemConfig(
          List.of(
              MotorConfig.leader(LEADER_MOTOR_ID, LEADER_NEUTRAL_MODE, LEADER_REVERSED),
              MotorConfig.follower(FOLLOWER_1_MOTOR_ID, FOLLOWER_1_NEUTRAL_MODE, FOLLOWER_1_REVERSED),
              MotorConfig.follower(FOLLOWER_2_MOTOR_ID, FOLLOWER_2_NEUTRAL_MODE, FOLLOWER_2_REVERSED)),
          new LeadMotorConfig(
              KP,
              KI,
              KD,
              KG,
              KS,
              KV,
              KA,
              SENSOR_TO_MECHANISM_RATIO,
              ROTOR_TO_SENSOR_RATIO,
              FOC_ENABLED),
          new MotionMagicConfig(MOTION_MAGIC_CRUISE_VELOCITY, MOTION_MAGIC_ACCELERATION),
          NAME,
          TORQUE_FF);

  // POWERLIB CUSTOM CONSTANTS START - DO NOT DELETE

  // POWERLIB CUSTOM CONSTANTS END - DO NOT DELETE
}
