package frc.robot.constants;

// Generated by PowerLib subsystem tool. Edit power-tool/generated/powerlib-subsystems.json, then run update.
// POWERLIB SUBSYSTEM ID: spindexer

import com.ctre.phoenix6.signals.NeutralModeValue;
import frc.powerlib.configs.LeadMotorConfig;
import frc.powerlib.configs.MotionMagicConfig;
import frc.powerlib.configs.MotorConfig;
import frc.powerlib.configs.VelocitySubsystemConfig;
import java.util.List;
import java.util.Optional;

public class SpindexerConstants {
  public static final int LEADER_MOTOR_ID = 30;
  public static final NeutralModeValue LEADER_NEUTRAL_MODE = NeutralModeValue.Brake;
  public static final boolean LEADER_REVERSED = false;
  public static final double KP = 0.1;
  public static final double KI = 0;
  public static final double KD = 0;
  public static final double KG = 0;
  public static final Optional<Double> KS = Optional.of(0.30415);
  public static final Optional<Double> KV = Optional.of(0.12429);
  public static final Optional<Double> KA = Optional.of(0.0034288);
  public static final double SENSOR_TO_MECHANISM_RATIO = 1;
  public static final double ROTOR_TO_SENSOR_RATIO = 1;
  public static final boolean FOC_ENABLED = true;
  public static final double TORQUE_FF = 0.0;
  public static final double MOTION_MAGIC_CRUISE_VELOCITY = 0;
  public static final double MOTION_MAGIC_ACCELERATION = 200;
  public static final String NAME = "Spindexer";

  public static final VelocitySubsystemConfig SPINDEXER_CONFIG =
      new VelocitySubsystemConfig(
          List.of(
              MotorConfig.leader(LEADER_MOTOR_ID, LEADER_NEUTRAL_MODE, LEADER_REVERSED)),
          new LeadMotorConfig(
              KP,
              KI,
              KD,
              KG,
              KS,
              KV,
              KA,
              SENSOR_TO_MECHANISM_RATIO,
              ROTOR_TO_SENSOR_RATIO,
              FOC_ENABLED),
          new MotionMagicConfig(MOTION_MAGIC_CRUISE_VELOCITY, MOTION_MAGIC_ACCELERATION),
          NAME,
          TORQUE_FF);

  // POWERLIB CUSTOM CONSTANTS START - DO NOT DELETE
  @frc.powerlib.tuning.TunableConstant
  public static volatile int LASER_1_CAN_ID = 31;
  @frc.powerlib.tuning.TunableConstant
  public static volatile int LASER_2_CAN_ID = 32;
  // POWERLIB CUSTOM CONSTANTS END - DO NOT DELETE
}
