package frc.robot.constants;

// Generated by PowerLib subsystem tool. Edit power-tool/generated/powerlib-subsystems.json, then run update.
// POWERLIB SUBSYSTEM ID: turret

import com.ctre.phoenix6.signals.NeutralModeValue;
import frc.powerlib.configs.CancoderConfig;
import frc.powerlib.configs.LeadMotorConfig;
import frc.powerlib.configs.MotionMagicConfig;
import frc.powerlib.configs.MotorConfig;
import frc.powerlib.configs.AbsolutePositionSubsystemConfig;
import java.util.List;
import java.util.Optional;

public class TurretConstants {
  public static final int LEADER_MOTOR_ID = 60;
  public static final NeutralModeValue LEADER_NEUTRAL_MODE = NeutralModeValue.Brake;
  public static final boolean LEADER_REVERSED = true;
  public static final double KP = 57;
  public static final double KI = 0;
  public static final double KD = 0;
  public static final double KG = 0;
  public static final Optional<Double> KS = Optional.empty();
  public static final Optional<Double> KV = Optional.empty();
  public static final Optional<Double> KA = Optional.empty();
  public static final double SENSOR_TO_MECHANISM_RATIO = -1;
  public static final double ROTOR_TO_SENSOR_RATIO = 48.166666666666664;
  public static final boolean FOC_ENABLED = false;
  public static final int CANCODER_ID = 61;
  public static final double CANCODER_MAGNET_OFFSET = 0.1255;
  public static final double CANCODER_DISCONTINUITY_POINT = 0.5;
  public static final double MOTION_MAGIC_CRUISE_VELOCITY = 3;
  public static final double MOTION_MAGIC_ACCELERATION = 60;
  public static final String NAME = "Turret";
  public static final String POSITION_UNITS = "degrees";
  public static final Optional<Double> DEFAULT_POSITION = Optional.of(0.0);

  public static final AbsolutePositionSubsystemConfig TURRET_CONFIG =
      new AbsolutePositionSubsystemConfig(
          List.of(
              MotorConfig.leader(LEADER_MOTOR_ID, LEADER_NEUTRAL_MODE, LEADER_REVERSED)),
          new LeadMotorConfig(
              KP,
              KI,
              KD,
              KG,
              KS,
              KV,
              KA,
              SENSOR_TO_MECHANISM_RATIO,
              ROTOR_TO_SENSOR_RATIO,
              FOC_ENABLED),
          new CancoderConfig(CANCODER_ID, CANCODER_MAGNET_OFFSET, CANCODER_DISCONTINUITY_POINT),
          new MotionMagicConfig(MOTION_MAGIC_CRUISE_VELOCITY, MOTION_MAGIC_ACCELERATION),
          NAME,
          POSITION_UNITS,
          DEFAULT_POSITION);

  // POWERLIB CUSTOM CONSTANTS START - DO NOT DELETE
  @frc.powerlib.tuning.TunableConstant
  public static volatile double TURRET_MIN = -0.481;
  @frc.powerlib.tuning.TunableConstant
  public static volatile double TURRET_MAX = 0.46;
  @frc.powerlib.tuning.TunableConstant
  public static volatile double TURRET_DEFAULT = 0;
  @frc.powerlib.tuning.TunableConstant
  public static volatile double TURRET_DIST_FROM_ROBOT_CENTER = -0.15875;
  @frc.powerlib.tuning.TunableConstant
  public static volatile double TURRET_RADIUS = 0.11596;
  @frc.powerlib.tuning.TunableConstant
  public static volatile double TURRET_LIMELIGHT_STATIC_OFFSET = -0.04279000000000001;
  @frc.powerlib.tuning.TunableConstant
  public static volatile double TURRET_SHOOT_ANGLE_TOLERANCE_DEG = 2;
  @frc.powerlib.tuning.TunableConstant
  public static volatile double SHOOT_MAX_DRIVETRAIN_SPEED_MPS = 0.5;
  @frc.powerlib.tuning.TunableConstant
  public static volatile double TURRET_CAMERA_Y_OFFSET = 0;
  public static final double[][] HOOD_ANGLES = {
            { 5.5, 0.135 },
            { 4.85, 0.105 },
            { 4.6, 0.09 },
            { 4.05, 0.08 },
            { 3.75, 0.07 },
            { 3.29, 0.06 },
            { 2.75, 0.05 },
            { 2.38, 0.04 },
            { 1.97, 0.03 },
            { 1.68, 0.02 }
    };
  public static final double[][] SHOOTER_SPEEDS = {
             { 5.5, 89},
            { 4.85, 84},
            { 4.6, 82},
            { 4.05, 79},
            { 3.75, 77},
            { 3.29, 74},
            { 2.75, 71},
            { 2.38, 67},
            { 1.97, 64},
            { 1.68, 62}
    };
  public static final double[][] FEEDER_SPEEDS = {
        { 5.5, 72},
        { 4.85, 68},
        { 4.6, 67},
        { 4.05, 66},
        { 3.75, 65},
        { 3.29, 65},
        { 2.75, 63},
        { 2.38, 61},
        { 1.97, 59},
        { 1.68, 58}
    };
  public static final frc.powerlib.math.LinearInterpolator HOOD_ANGLE_INTERPOLATOR = new frc.powerlib.math.LinearInterpolator(HOOD_ANGLES);
  public static final frc.powerlib.math.LinearInterpolator SHOOTER_VELOCITY_INTERPOLATOR = new frc.powerlib.math.LinearInterpolator(SHOOTER_SPEEDS);
  public static final frc.powerlib.math.LinearInterpolator FEEDER_VELOCITY_INTERPOLATOR = new frc.powerlib.math.LinearInterpolator(FEEDER_SPEEDS);
  // POWERLIB CUSTOM CONSTANTS END - DO NOT DELETE
}
