package frc.robot.characterization;

// Generated by PowerLib subsystem tool. Edit power-tool/generated/powerlib-subsystems.json, then run update.
// POWERLIB SUBSYSTEM ID: intakeRoller

import static edu.wpi.first.units.Units.Radians;
import static edu.wpi.first.units.Units.RadiansPerSecond;
import static edu.wpi.first.units.Units.Volts;

import com.ctre.phoenix6.SignalLogger;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.powerlib.subsystems.VelocitySubsystem;

public class IntakeRollerCharacterization {
  private final VelocitySubsystem subsystem;
  private final SysIdRoutine routine;
  private final double[] lastVoltage = {0};

  public IntakeRollerCharacterization(VelocitySubsystem subsystem) {
    this.subsystem = subsystem;
    this.routine =
        new SysIdRoutine(
            new SysIdRoutine.Config(
                null,
                Volts.of(4),
                null,
                state -> SignalLogger.writeString("SysIdIntakeRoller_State", state.toString())),
            new SysIdRoutine.Mechanism(
                voltage -> {
                  lastVoltage[0] = voltage.in(Volts);
                  subsystem.setVoltage(voltage.in(Volts));
                },
                log -> {
                  var motor = subsystem.getVelocityMotor();
                  if (motor == null) {
                    return;
                  }
                  double posRot = motor.getRotorPosition().getValueAsDouble();
                  double velRps = motor.getRotorVelocity().getValueAsDouble();
                  log
                      .motor("IntakeRoller")
                      .voltage(Volts.of(lastVoltage[0]))
                      .angularPosition(Radians.of(posRot * 2 * Math.PI))
                      .angularVelocity(RadiansPerSecond.of(velRps * 2 * Math.PI));
                },
                subsystem,
                "IntakeRoller"));
  }

  public Command quasistaticForward() {
    return withLogging(routine.quasistatic(SysIdRoutine.Direction.kForward));
  }

  public Command quasistaticReverse() {
    return withLogging(routine.quasistatic(SysIdRoutine.Direction.kReverse));
  }

  public Command dynamicForward() {
    return withLogging(routine.dynamic(SysIdRoutine.Direction.kForward));
  }

  public Command dynamicReverse() {
    return withLogging(routine.dynamic(SysIdRoutine.Direction.kReverse));
  }

  private Command withLogging(Command command) {
    return Commands.sequence(
        Commands.runOnce(() -> SignalLogger.start()),
        command,
        Commands.runOnce(() -> SignalLogger.stop()));
  }
}
